import MiniSearch, { type Options, type SearchOptions } from 'minisearch';
import type { Lang, Skill, Taxonomy, TaxonomyNode } from '../types.ts';
import { skillSlug } from './slug.ts';

/**
 * One searchable entry in the typo-rescue index. Names and aliases only — never descriptions.
 * `path` is base-relative; the client applies withBase() at navigation time so the artifact can
 * be generated by a plain Node script and stays correct under any deployment base.
 */
export interface RescueDoc {
  id: string;
  kind: 'skill' | 'node';
  name: string;
  aliases: string;
  path: string;
}

function aliasIndex(taxonomy: Taxonomy): Map<string, string[]> {
  const byTarget = new Map<string, string[]>();
  for (const [alias, target] of Object.entries(taxonomy.aliases)) {
    const list = byTarget.get(target) ?? [];
    list.push(alias);
    byTarget.set(target, list);
  }
  return byTarget;
}

function aliasTermsFor(slug: string, byTarget: Map<string, string[]>): string[] {
  const tail = slug.includes('/') ? slug.slice(slug.lastIndexOf('/') + 1) : slug;
  return Array.from(new Set([
    ...(byTarget.get(slug) ?? []),
    ...(byTarget.get(tail) ?? []),
    ...slug.split(/[/-]+/).filter((part) => part.length > 1),
  ]));
}

function flattenNodes(nodes: TaxonomyNode[]): TaxonomyNode[] {
  const out: TaxonomyNode[] = [];
  for (const node of nodes) {
    out.push(node);
    if (node.children) out.push(...flattenNodes(node.children));
  }
  return out;
}

export function buildRescueDocs(skills: Skill[], taxonomy: Taxonomy, lang: Lang): RescueDoc[] {
  const byTarget = aliasIndex(taxonomy);
  const docs: RescueDoc[] = [];

  for (const node of flattenNodes(taxonomy.domains)) {
    docs.push({
      id: `node:${node.slug}`,
      kind: 'node',
      name: node.name[lang],
      aliases: aliasTermsFor(node.slug, byTarget).join(' '),
      // Rule 4: the catalog is the only list surface, so a node suggestion is a filtered catalog.
      path: `/${lang}/catalog/?subdomain=${node.slug}`,
    });
  }

  // §5.1: an entry evicted by the per-subdomain cap keeps its page but leaves every search surface.
  for (const skill of skills.filter((entry) => entry.listed)) {
    docs.push({
      id: skill.id,
      kind: 'skill',
      name: skill.name,
      aliases: skill.repo.split(/[/\-_.]+/).filter((part) => part.length > 1).join(' '),
      path: `/${lang}/skills/${skillSlug(skill)}/`,
    });
  }

  return docs;
}

/** Index shape. `aliases` is searchable but not stored, keeping the payload small. */
export const RESCUE_OPTIONS: Options<RescueDoc> = {
  idField: 'id',
  fields: ['name', 'aliases'],
  storeFields: ['kind', 'name', 'path'],
};

/**
 * fuzzy 0.2 gives maxDistance = round(term.length * 0.2):
 * "kubernets" -> 2 (needs 1), "terrafrom" -> 2 (needs 2), "clude" -> 1 (needs 1).
 */
export const RESCUE_SEARCH_OPTIONS: SearchOptions = {
  prefix: true,
  fuzzy: 0.2,
  combineWith: 'OR',
  boost: { name: 2 },
};

export interface RescueSuggestion {
  id: string;
  kind: 'skill' | 'node';
  name: string;
  /** Base-relative. Apply withBase() before navigating. */
  path: string;
}

export function createRescueIndex(docs: RescueDoc[]): MiniSearch<RescueDoc> {
  const index = new MiniSearch<RescueDoc>(RESCUE_OPTIONS);
  index.addAll(docs);
  return index;
}

export function suggestRescue(
  index: MiniSearch<RescueDoc>,
  query: string,
  limit = 7,
): RescueSuggestion[] {
  const trimmed = query.trim();
  if (trimmed.length < 2) return [];
  return index
    .search(trimmed, RESCUE_SEARCH_OPTIONS)
    .slice(0, limit)
    .map((hit) => ({
      id: String(hit.id),
      kind: hit.kind as 'skill' | 'node',
      name: hit.name as string,
      path: hit.path as string,
    }));
}
